LAUNCH_METHOD: '3' #0=Menu, 1=Movie library, 2= TV Show library, 3= Both consecutively
PLEX_URL: 'http://localhost:32400'
PLEX_TOKEN: 'YOUR_PLEX_TOKEN'

TV_LIBRARY_NAME: 'TV Shows'
TV_GENRES_TO_SKIP:
  - 'Talk Show'
  - 'Stand-Up'
  - 'News'

MOVIE_LIBRARY_NAME: 'Movies, Movies(4K+REMUX)'
MOVIE_GENRES_TO_SKIP:
  - 'Short'
  - 'Concert'

CHECK_PLEX_PASS_TRAILERS: true
DOWNLOAD_TRAILERS: true
PREFERRED_LANGUAGE: original
REFRESH_METADATA: true
SHOW_YT_DLP_PROGRESS: true
YT_DLP_COOKIES_FROM_BROWSER: "chrome"  # or firefox, edge, safari, etc.

SKIP_CHANNELS:
  - "Starlight Cinema"
  - "fake trailers"
  - "Black And White Media"
  - "CircleX Creations"
  - "New Movie Updates"